### ISSUE TITLE
balancer generates EINVAL num of osd pairs

### ISSUE THREAD

**Issue by stuartthebruce** [TheJJ/ceph-balancer#14]
<pre>
./placementoptimizer.py -v balance --max-pg-moves 1000 --max-full-move-attempts=1000
</pre>
generates pg-upmap-items that,
<pre>
Error EINVAL: num of osd pairs (4) > pool size (3)
</pre>
For example, here are some large OSD lists for a triply replicated pool,
<pre>
ceph osd pg-upmap-items 14.36e7 2020 1591 2019 1612 1591 1438 1612 597
ceph osd pg-upmap-items 14.12c6 1093 1767 2018 638
ceph osd pg-upmap-items 14.2f63 817 1357 710 1613 1357 1366 1613 630
ceph osd pg-upmap-items 14.2790 1312 674 822 1763 674 1740 1763 1470 1740 1445 1470 601
</pre>
Taking a closer look at the last entry there are indeed OSD listed that are not used by that PG,
<pre>
[root@ceph-admin ~]# ceph pg dump | awk '$1 == "14.2790"'
dumped all
14.2790     2214                   0         0          0        0    8615245675            0           0    887       887                 active+clean  2022-08-01T07:56:09.531220-0700    858000'9325   871388:788167                             [180,1312,605]         180                             [180,1312,605]             180    858000'9325  2022-08-01T07:56:09.530894-0700      858000'9325  2022-08-01T07:56:09.530894-0700              0
</pre>

**Comment by TheJJ** [comment]
Thx. It seems that the mapping generator doesn't trim duplicate entries (2019 1612 and 1612 597 has to be replaced by 2019 597).

**Comment by TheJJ** [comment]
can you please try if this still is a problem? if yes, please notify me and send a recend state file, thanks!
