### ISSUE TITLE
Do Not Skip the Entire Pool When Balancing PGs

### ISSUE THREAD

**Issue by xuyungit** [TheJJ/ceph-balancer#24]
Hello,

In one of my small clusters, the balancer attempted to move the first PG of a pool, but it did not find any suitable target and skipped this pool completely. So the balancer generated no move suggestion of this pool. I think the balancer should have checked if the rest of the PGs in the same pool could be moved to other OSDs. 

ps: Related logic is at line from 2126 to 2128

**Comment by TheJJ** [comment]
This is basically #18, but I don't understand why it's possible moving other PGs of the same pool if one fails.
If there's no suitable spot for a PG, why is there a suitable spot for another PG of same size and pool?

**Comment by xuyungit** [comment]
Let's imagine a scenario: we have four hosts, each with several OSDs. A PG is distributed to hosts 1, 2 and 3, and we want to move it from the OSD on host 1 to another OSD (host-based failure domain). OSDs on hosts 2 and 3 cannot be the candidate due to the CRUSH rule. At the same time, OSDs on hosts 1 and 4 already have enough PG count of this pool's OSDs, so the algorithm cannot find a suitable candidate for this PG to move to.

Another PG of the same pool is assigned to hosts 1, 3 and 4, so it's possible to move the PG to an OSD on host 2.

**Comment by TheJJ** [comment]
Can you please send me your state dump file to `jj at sft dot lol` please? Then I can reproduce locally and check if it's a bug in the code :)

**Comment by xuyungit** [comment]
Unfortunately, the Ceph environment I used for testing had already been uninstalled. I'll try to dump cluster state when I get a new testbed.
