### ISSUE TITLE
Failing when using --source-osds

### ISSUE THREAD

**Issue by kaistian** [TheJJ/ceph-balancer#45]
When using `--source-osds` it fails with `AttributeError: 'Namespace' object has no attribute '_source_osds'`

This line
https://github.com/TheJJ/ceph-balancer/blob/38e5d5f183c25b118f4564d0bdfe961553b9f0f0/placementoptimizer.py#L4633

the args should be `args.source_osds`

**Comment by TheJJ** [comment]
fixed by #51
